### ISSUE TITLE
Do you plan supporting other slave platforms?

### ISSUE THREAD

**Issue by upintheairsheep** [Whop42/LinuxConvert#3]
Hello, do you plan on supporting other slave platforms to transfer to Linux to in the future, such as macOS, ChromeOS Flex, Android, and iOS/iPadOS? I suggest you look into getting the software integrated with (GNOME or KDE)'s setup wizards, so users of these platforms can migrate easily when dualbooting and make consumer-based Linux-based devices more convenient.

**Comment by Whop42** [comment]
Unfortunately, I do not plan on supporting platforms other than Windows. The problem with supporting multiple OSes is that it exponentially increases the amount of work I have to do with supporting applications.
